import { expect, test } from '@playwright/test'
import { login } from './helpers'

const count = async (page: import('@playwright/test').Page) => Number((await page.getByTestId('result-count').locator('b').innerText()).replace(/,/g, ''))

async function addCondition(page: import('@playwright/test').Page, field: string, operator: string, value?: string, valueLabel = 'Value') {
  await page.getByRole('button', { name: 'Condition', exact: true }).first().click()
  const row = page.getByTestId('condition').last()
  await row.getByLabel('Field').selectOption({ label: field })
  await row.getByLabel('Operator').selectOption({ label: operator })
  if (value !== undefined) await row.getByLabel(valueLabel).fill(value)
}

test('query builder: conditions narrow results live and OR widens them', async ({ page }) => {
  await login(page)
  await page.getByRole('link', { name: 'Lists & Views' }).click()
  await expect(page.getByTestId('results')).toBeVisible()
  const all = await count(page)
  expect(all).toBeGreaterThan(100)
  await addCondition(page, 'Loan maturity', 'is within next (days)', '365', 'Days')
  await expect.poll(() => count(page)).toBeLessThan(all)
  const maturing = await count(page)
  await addCondition(page, 'Property type', 'is')
  await page.getByTestId('condition').last().getByLabel('Value').selectOption('industrial')
  await expect.poll(() => count(page)).toBeLessThan(maturing)
  await page.getByLabel('Match operator').selectOption('or')
  await expect.poll(() => count(page)).toBeGreaterThan(maturing)
})

test('related-record condition: owners whose properties have loans maturing soon', async ({ page }) => {
  await login(page)
  await page.getByRole('link', { name: 'Lists & Views' }).click()
  await page.getByLabel('Entity').selectOption('contact')
  await addCondition(page, 'Holdings: Loan maturity', 'is within next (days)', '365', 'Days')
  await expect.poll(() => count(page)).toBeGreaterThan(0)
  await expect(page.getByRole('columnheader', { name: 'Name', exact: true })).toBeVisible()
})

test('invalid combinations never reach the user as a broken table: the builder only offers valid operators', async ({ page }) => {
  await login(page)
  await page.getByRole('link', { name: 'Lists & Views' }).click()
  await page.getByRole('button', { name: 'Condition', exact: true }).first().click()
  await page.getByTestId('condition').last().getByLabel('Field').selectOption({ label: 'Hold intent' })
  const ops = await page.getByTestId('condition').last().getByLabel('Operator').locator('option').allInnerTexts()
  expect(ops).not.toContain('>')
  expect(ops).toContain('is one of')
})

test('save a view and a dynamic list, then snapshot the list', async ({ page }) => {
  await login(page)
  await page.getByRole('link', { name: 'Lists & Views' }).click()
  await addCondition(page, 'Hold period (years)', '≥', '10')
  await page.getByRole('button', { name: 'Save view' }).click()
  await page.getByLabel('Name').fill('E2E long holds')
  await page.getByLabel('Share with the team').check()
  await page.getByRole('dialog').getByRole('button', { name: 'Save', exact: true }).click()
  await page.getByRole('tab', { name: 'Saved views' }).click()
  await expect(page.getByTestId('views').getByText('E2E long holds')).toBeVisible()
  await page.getByTestId('views').getByText('E2E long holds').click()
  await expect(page.getByTestId('result-count')).toBeVisible()
  await page.getByRole('button', { name: 'Make list' }).click()
  await page.getByRole('dialog').getByLabel('Name').fill('E2E long-hold list')
  await page.getByRole('dialog').getByRole('button', { name: 'Create list' }).click()
  await page.getByRole('tab', { name: 'Lists', exact: true }).click()
  await page.getByTestId('lists').getByText('E2E long-hold list').click()
  await expect(page.getByText('recomputed on every view')).toBeVisible()
  await page.getByRole('button', { name: 'Snapshot' }).click()
  await expect(page.getByTestId('lists').getByText(/E2E long-hold list \(snapshot/)).toBeVisible()
})

test('tag selected records and find them under Tags', async ({ page }) => {
  await login(page)
  await page.getByRole('link', { name: 'Lists & Views' }).click()
  await page.getByLabel('Entity').selectOption('contact')
  await expect(page.getByTestId('results').locator('tbody tr').first()).toBeVisible()
  await page.getByLabel(/^Select /).nth(0).check()
  await page.getByLabel(/^Select /).nth(1).check()
  await page.getByRole('button', { name: 'Tag selected' }).click()
  await page.getByLabel('Tag', { exact: true }).fill('E2E Priority Calls')
  await page.getByRole('button', { name: 'Apply tag' }).click()
  await page.getByRole('tab', { name: 'Tags' }).click()
  await page.getByTestId('tags').getByText('e2e priority calls').click()
  await expect.poll(() => count(page)).toBe(2)
})

test('custom fields: seeded values show and can be edited with backend validation', async ({ page }) => {
  await login(page)
  await page.getByRole('link', { name: 'Properties' }).click()
  await page.getByLabel('Hold period').selectOption('10')
  await page.locator('tbody tr').first().click()
  const card = page.getByTestId('custom-fields')
  await expect(card).toBeVisible()
  await expect(card.getByText('Roof age (years)')).toBeVisible()
  await card.getByRole('button', { name: 'Edit' }).click()
  await card.getByLabel('Roof age (years)').fill('11')
  await card.getByLabel('Seller motivation').selectOption('Retirement')
  await card.getByRole('button', { name: 'Save' }).click()
  await expect(card.getByText('Retirement')).toBeVisible()
  await expect(card.getByText('11')).toBeVisible()
})

test('admin defines a required field and the backend enforces it on create', async ({ page }) => {
  await login(page)
  await page.getByRole('link', { name: 'Lists & Views' }).click()
  await page.getByRole('tab', { name: 'Custom fields' }).click()
  await page.getByLabel('Field entity').selectOption('company')
  await page.getByLabel('Field label').fill('Compliance contact')
  await page.getByLabel('Required').check()
  await page.getByRole('button', { name: 'Add field' }).click()
  await expect(page.getByRole('cell', { name: 'Compliance contact' })).toBeVisible()
  await page.getByRole('link', { name: 'Companies' }).click()
  await page.getByRole('button', { name: 'New entity' }).click()
  await page.getByLabel('Name', { exact: true }).fill('E2E Required Field Holdings LLC')
  await page.getByRole('button', { name: 'Create entity' }).click()
  await expect(page.getByRole('dialog').getByRole('alert')).toContainText('Compliance contact is required')
  // retire it so the rest of the suite is unaffected; retired fields keep their data but stop applying
  await page.keyboard.press('Escape')
  await page.getByRole('link', { name: 'Lists & Views' }).click()
  await page.getByRole('tab', { name: 'Custom fields' }).click()
  await page.getByRole('row', { name: /Compliance contact/ }).getByRole('button', { name: 'Retire' }).click()
  await expect(page.getByRole('row', { name: /Compliance contact/ }).getByText('retired')).toBeVisible()
})

test('restricted custom fields are invisible to assistants', async ({ page }) => {
  await login(page, 'priya@resha.group')
  await page.getByRole('link', { name: 'Deals', exact: true }).click()
  await page.getByTestId('deal-card').first().click()
  await expect(page.getByTestId('custom-fields').getByText('Referral fee note')).toHaveCount(0)
})
