import { expect, test } from '@playwright/test'
import { login } from './helpers'

const tag = () => Math.random().toString(36).slice(2, 8)

test('admin sees users, roles and the role matrix; changing a role is enforced', async ({ page }) => {
  const t = tag()
  await login(page)
  await page.getByRole('link', { name: 'Admin & Audit' }).click()
  await expect(page.getByTestId('users')).toBeVisible()
  await expect(page.getByText('What each role can do')).toBeVisible()
  await page.getByRole('button', { name: 'Add user' }).click()
  await page.getByLabel('User name').fill(`E2E Reader ${t}`)
  await page.getByLabel('User email').fill(`reader${t}@e2e.test`)
  await page.getByLabel('User role').selectOption('read_only')
  await page.getByLabel('User password').fill('longpass1')
  await page.getByRole('button', { name: 'Create user' }).click()
  await expect(page.getByTestId('users').getByText(`reader${t}@e2e.test`)).toBeVisible()
  await page.getByLabel(`Role for E2E Reader ${t}`).selectOption('broker')
  await expect(page.getByLabel(`Role for E2E Reader ${t}`)).toHaveValue('broker')
})

test('deactivating a user who owns records requires reassignment', async ({ page }) => {
  await login(page)
  await page.getByRole('link', { name: 'Admin & Audit' }).click()
  await page.getByLabel('Deactivate Kevin Park').click()
  await expect(page.getByText(/Owns \d+ items/)).toBeVisible()
  await page.getByRole('button', { name: 'Reassign and deactivate' }).click()
  await expect(page.getByRole('dialog').getByRole('alert')).toContainText('Reassign them first')
  await page.getByLabel('Reassign to').selectOption({ label: 'Dana Whitfield' })
  await page.getByRole('button', { name: 'Reassign and deactivate' }).click()
  await expect(page.getByTestId('users').getByRole('row', { name: /Kevin Park/ }).getByText('Inactive')).toBeVisible()
  // the deactivated user can no longer sign in
  await page.getByLabel('Sign out').click()
  await page.goto('/login')
  await page.getByLabel('Email').fill('kevin@resha.group')
  await page.getByLabel('Password').fill('demo1234')
  await page.getByRole('button', { name: 'Sign in' }).click()
  await expect(page.getByRole('alert')).toContainText('Invalid')
})

test('audit trail: filter by record type and action, open an event', async ({ page }) => {
  await login(page)
  await page.getByRole('link', { name: 'Admin & Audit' }).click()
  await page.getByRole('tab', { name: 'Audit trail' }).click()
  await expect(page.getByTestId('audit').locator('tbody tr').first()).toBeVisible()
  await page.getByLabel('Entity type').selectOption('deals')
  await page.getByLabel('Action', { exact: true }).selectOption('update')
  await expect(page.getByTestId('audit').locator('tbody tr').first()).toBeVisible()
  for (const t of await page.getByTestId('audit').locator('tbody tr td:nth-child(4)').allInnerTexts()) expect(t).toMatch(/^deals/)
  await page.getByTestId('audit').locator('tbody tr').first().click()
  await expect(page.getByRole('dialog')).toContainText('deals')
})

test('rule actions are attributed to the rule in the audit trail', async ({ page }) => {
  await login(page)
  await page.getByRole('link', { name: 'Admin & Audit' }).click()
  await page.getByRole('tab', { name: 'Audit trail' }).click()
  await page.getByLabel('Filter by actor').fill('rule:')
  await expect(page.getByTestId('audit').locator('tbody tr').first()).toBeVisible()
})

test('API tokens are shown once, scoped to the role, and revocable', async ({ page }) => {
  const t = tag()
  await login(page, 'tyler@1880capital.com')
  await page.getByRole('link', { name: 'Admin & Audit' }).click()
  await expect(page.getByRole('tab', { name: 'Users & roles' })).toHaveCount(0)
  await expect(page.getByLabel('delete')).toHaveCount(0)
  await page.getByLabel('Token name').fill(`Integration ${t}`)
  await page.getByRole('button', { name: 'Create token' }).click()
  const code = page.getByRole('status').locator('code')
  await expect(code).toContainText('trg_')
  const token = await code.innerText()
  const res = await page.request.get('/api/contacts?limit=1', { headers: { Authorization: `Bearer ${token}` } })
  expect(res.status()).toBe(200)
  const denied = await page.request.post('/api/contacts', { data: { first_name: 'No', last_name: 'Scope' }, headers: { Authorization: `Bearer ${token}` } })
  expect(denied.status()).toBe(403)
  await page.getByRole('row', { name: new RegExp(`Integration ${t}`) }).getByRole('button', { name: 'Revoke' }).click()
  await expect(page.getByRole('row', { name: new RegExp(`Integration ${t}`) }).getByText('revoked')).toBeVisible()
  expect((await page.request.get('/api/contacts?limit=1', { headers: { Authorization: `Bearer ${token}` } })).status()).toBe(401)
})

test('visibility setting: switching to team-scoped is admin only', async ({ page }) => {
  await login(page, 'maria@resha.group')
  await page.getByRole('link', { name: 'Admin & Audit' }).click()
  await page.getByRole('tab', { name: 'Settings' }).click()
  await expect(page.getByLabel('Team-scoped')).toBeDisabled()
  await expect(page.getByText('Only admins can change this setting.')).toBeVisible()
})

test('automation: seeded rules show plain-language triggers, preview and a real action log', async ({ page }) => {
  await login(page)
  await page.getByRole('link', { name: 'Automation' }).click()
  const rules = page.getByTestId('rules')
  await expect(rules.getByText('Loan maturity: 6-month alert')).toBeVisible()
  await expect(rules.getByText(/When:.*before a property's loan maturity date/).first()).toBeVisible()
  const card = rules.locator('div.rounded-lg', { hasText: 'Owner untouched 120 days: re-engage' }).first()
  await card.getByRole('button', { name: 'Preview' }).click()
  await expect(page.getByTestId('rule-matched')).not.toHaveText('0')
  await page.keyboard.press('Escape')
  await card.getByRole('button', { name: 'Action log' }).click()
  await expect(page.getByTestId('rule-detail').locator('li').first()).toContainText('create_task')
})

test('automation: build a rule, run it twice, and it never repeats', async ({ page }) => {
  const t = tag()
  await login(page)
  await page.getByRole('link', { name: 'Automation' }).click()
  await page.getByRole('button', { name: 'New rule' }).click()
  await page.getByLabel('Rule name').fill(`E2E rule ${t}`)
  await page.getByLabel('Rule entity').selectOption('contact')
  await page.getByLabel('Trigger').selectOption('scheduled')
  await page.getByLabel('Only if conditions match').check()
  await page.getByRole('button', { name: 'Condition', exact: true }).click()
  await page.getByTestId('condition').last().getByLabel('Field').selectOption({ label: 'Tags' })
  await page.getByTestId('condition').last().getByLabel('Operator').selectOption({ label: 'contains' })
  await page.getByTestId('condition').last().getByLabel('Value').fill('vip')
  await page.getByLabel('Task subject').fill(`E2E follow up ${t} for {name}`)
  await page.getByRole('button', { name: 'Create rule' }).click()
  const card = page.getByTestId('rules').locator('div.rounded-lg', { hasText: `E2E rule ${t}` }).first()
  await expect(card).toBeVisible()
  await card.getByRole('button', { name: 'Run now' }).click()
  const matched = Number(await page.getByTestId('rule-matched').innerText())
  expect(matched).toBeGreaterThan(0)
  await expect(page.getByRole('dialog')).toContainText('actions taken')
  await page.keyboard.press('Escape')
  await card.getByRole('button', { name: 'Run now' }).click()
  await expect(page.getByRole('dialog')).toContainText('0 actions taken')
})

test('automation: brokers can view rules but not create or run them (the API refuses even an email action)', async ({ page }) => {
  await login(page, 'dana@resha.group')
  await page.getByRole('link', { name: 'Automation' }).click()
  await expect(page.getByRole('button', { name: 'New rule' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Run now' })).toHaveCount(0)
  const res = await page.request.post('/api/rules', { data: { name: 'x', entity: 'contact', trigger_type: 'record_created', actions: [{ type: 'send_email', params: {} }] }, headers: { Authorization: `Bearer ${await page.evaluate(() => localStorage.getItem('trg_token'))}` } })
  expect(res.status()).toBe(403)
})
