import { expect, test } from '@playwright/test'
import { login } from './helpers'

const tag = () => Math.random().toString(36).slice(2, 8)

test('email inbox shows seeded mail, privacy controls and the provider notice', async ({ page }) => {
  await login(page)
  await page.getByRole('link', { name: /^Email/  }).click()
  await expect(page.getByTestId('provider-notice')).toContainText('Sending from the CRM is off')
  await expect(page.getByTestId('mail-row').first()).toBeVisible()
  expect(await page.getByTestId('mail-row').count()).toBeGreaterThan(5)
  const sel = page.getByTestId('mail-row').first().getByRole('combobox')
  await sel.selectOption('team_full')
  await expect(sel).toHaveValue('team_full')
  await page.getByRole('button', { name: 'Needs a home' }).click()
  await expect(page.getByTestId('mail-row').first().getByText('Not linked to any record')).toBeVisible()
})

test('exclusion rules are added and removed', async ({ page }) => {
  const t = tag()
  await login(page)
  await page.goto('/inbox')
  await page.getByRole('tab', { name: 'Privacy rules' }).click()
  await page.getByLabel('Rule value').fill(`${t}.example`)
  await page.getByRole('button', { name: 'Add rule' }).click()
  await expect(page.getByTestId('rules').getByText(`${t}.example`)).toBeVisible()
  await page.getByLabel(`Remove ${t}.example`).click()
  await expect(page.getByTestId('rules').getByText(`${t}.example`)).toHaveCount(0)
})

test('bulk email can be prepared and checked but not sent until a provider is chosen', async ({ page }) => {
  const t = tag()
  await login(page)
  await page.goto('/inbox')
  await page.getByRole('tab', { name: 'Templates & bulk' }).click()
  await expect(page.getByTestId('template').first()).toBeVisible()
  await page.getByLabel('Bulk name').fill(`E2E blast ${t}`)
  await page.getByLabel('Bulk template').selectOption({ index: 1 })
  await page.getByLabel('Bulk list').selectOption({ index: 1 })
  await page.getByRole('button', { name: 'Prepare and check recipients' }).click()
  await expect(page.getByTestId('bulk-result')).toContainText('Eligible')
  await page.getByRole('button', { name: 'Send', exact: true }).click()
  await expect(page.getByTestId('send-blocked')).toContainText('No mail provider')
  await expect(page.getByTestId('bulk-row').filter({ hasText: `E2E blast ${t}` })).toBeVisible()
})

test('calendar tab lists meetings', async ({ page }) => {
  await login(page)
  await page.goto('/inbox')
  await page.getByRole('tab', { name: 'Calendar' }).click()
  await expect(page.getByTestId('event-list').locator('> div').first()).toBeVisible()
})

test('contact timeline includes captured email', async ({ page }) => {
  await login(page)
  await page.goto('/contacts/80')
  await expect(page.getByTestId('email-row').first()).toBeVisible()
})

test('field mode: quick note saves, caller lookup matches, starred list shows', async ({ page }) => {
  const t = tag()
  await login(page)
  await page.getByRole('link', { name: 'Field Mode' }).click()
  await page.getByLabel('Find a record').fill('Edward Morales')
  await page.getByRole('button', { name: /Edward Morales/ }).first().click()
  await expect(page.getByTestId('picked')).toContainText('Edward Morales')
  await page.getByLabel('Quick text').fill(`Walked the site ${t}`)
  await page.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(page.getByTestId('flash')).toContainText('Saved to')
  await page.goto('/contacts/1')
  await expect(page.getByText(`Walked the site ${t}`)).toBeVisible()
  await page.goto('/m')
  await page.getByLabel('Caller phone').fill('(619) 857-9628')
  await expect(page.getByTestId('caller-result')).toContainText('Edward Morales')
  await page.getByLabel('Caller phone').fill('(310) 555-0000')
  await expect(page.getByTestId('caller-result')).toContainText('No match')
  await expect(page.getByTestId('starred').locator('> div').first()).toBeVisible()
})

test('field mode: address lookup returns owner and principals', async ({ page }) => {
  await login(page)
  await page.goto('/m')
  await page.getByLabel('Address lookup').fill('Anaheim Blvd')
  await expect(page.getByTestId('address-results').locator('> div').first()).toBeVisible()
  await expect(page.getByTestId('address-results')).toContainText('LLC')
})

test('field mode: a note taken offline is queued and syncs when the connection returns', async ({ page, context }) => {
  const t = tag()
  await login(page)
  await page.goto('/m')
  await page.getByLabel('Find a record').fill('Edward Morales')
  await page.getByRole('button', { name: /Edward Morales/ }).first().click()
  await context.setOffline(true)
  await expect(page.getByTestId('net-status')).toContainText('Offline')
  await page.getByLabel('Quick text').fill(`Offline note ${t}`)
  await page.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(page.getByTestId('flash')).toContainText('Offline: queued')
  await expect(page.getByTestId('queue-count')).toContainText('1 waiting')
  await context.setOffline(false)
  await expect(page.getByTestId('queue-count')).toHaveCount(0, { timeout: 15000 })
  await page.goto('/contacts/1')
  await expect(page.getByText(`Offline note ${t}`)).toBeVisible()
})
